routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\BahanBakuController;
use App\Http\Controllers\BerandaController;
use App\Http\Controllers\BillOfMaterialController;
use App\Http\Controllers\DaftarPengirimanController;
use App\Http\Controllers\ModelAndaController;
use App\Http\Controllers\ModelBajuPelangganController;
use App\Http\Controllers\PelangganController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\DaftarProgresController;
use App\Http\Controllers\InformasiUkuranController;
use App\Http\Controllers\JadwalProgresController;
use App\Http\Controllers\JasaEkspedisiController;
use App\Http\Controllers\KolomRakController;
use App\Http\Controllers\LaporanTertanggungController;
use App\Http\Controllers\PengunaanBahanBakuController;
use App\Http\Controllers\RealisasiProgresController;
use App\Http\Controllers\TransaksiBahanBakuController;
use App\Http\Controllers\TransaksiController;
use App\Http\Controllers\UkuranPriaController;
use App\Http\Controllers\UkuranWanitaController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

// Route::get('/dashboard', function () {
//     return view('beranda');
// })->middleware(['auth'])->name('dashboard');

Route::middleware(['auth'])->group(function () {

    Route::get('/dashboard', [BerandaController::class, 'dashboard'])->name('dashboard');

    Route::prefix('bahan-baku')->group(function () {
        Route::get('tambah-detail-transaksi-bahanbaku/{id}', [TransaksiBahanBakuController::class, 'createDetail'])->name('transaksi.bahanbaku.detail.create');
        Route::post('save-detail-transaksi-bahanbaku', [TransaksiBahanBakuController::class, 'saveDetail'])->name('transaksi.bahanbaku.save.detail');
        Route::get('edit-detail-transaksi-bahanbaku/{id}', [TransaksiBahanBakuController::class, 'editDetailTransaksi'])->name('transaksi.bahanbaku.detail.edit');
        Route::put('update-detail-transaksi-bahanbaku/{id}', [TransaksiBahanBakuController::class, 'updateDetailTransaksi'])->name('transaksi.bahanbaku.update.detail');
        Route::put('update-transaksi-totalbayar/{id}/update', [TransaksiBahanBakuController::class, 'updateTransaksiTotalbayar'])->name('transaksi.update.totalbayar');
        Route::get('get-ajax-bahan-baku/{id}', [TransaksiBahanBakuController::class, 'getAjaxBahanBaku'])->name('get-ajax-bahan-baku');
        Route::get('tambah-detail-bom/{id}', [BillOfMaterialController::class, 'createDetail'])->name('bom.detail.create');
        Route::post('save-detail-bom', [BillOfMaterialController::class, 'saveDetail'])->name('bom.detail.save');
        Route::get('edit-detail-bom/{id}', [BillOfMaterialController::class, 'editDetail'])->name('bom.detail.edit');
        Route::put('update-detail-bom/{id}', [BillOfMaterialController::class, 'updateDetail'])->name('bom.detail.update');



        Route::resource('transaksi-bahanbaku', TransaksiBahanBakuController::class);
        Route::resource('supplier', SupplierController::class);
        Route::resource('bahanbaku', BahanBakuController::class);
        Route::resource('kolomrak', KolomRakController::class);
        Route::resource('bom', BillOfMaterialController::class);
    });

    Route::prefix('pemesanan')->group(function () {
        Route::prefix('transaksi')->group(function () {
            Route::get('tambah-detail-transaksi/{id}', [TransaksiController::class, 'createDetailTransaksi'])->name('transaksi.detail.create');
            Route::post('save-detail-transaksi', [TransaksiController::class, 'saveDetail'])->name('transaksi.save.detail');
            Route::get('edit-detail-transaksi/{id}', [TransaksiController::class, 'editDetailTransaksi'])->name('transaksi.detail.edit');
            Route::post('update-detail-transaksi', [TransaksiController::class, 'updateDetailTransaksi'])->name('transaksi.update.detail');
            Route::get('tambah-detail-transaksi-ukuran/{id}', [TransaksiController::class, 'createDetailTransaksiUkuran'])->name('transaksi.detail.ukuran.create');
            Route::post('save-detail-transaksi-ukuran', [TransaksiController::class, 'saveDetailUkuran'])->name('transaksi.save.detail.ukuran');
            Route::get('edit-detail-transaksi-ukuran/{id}', [TransaksiController::class, 'editDetailUkuran'])->name('transaksi.edit.detail.ukuran');
            Route::post('update-detail-transaksi-ukuran', [TransaksiController::class, 'updateDetailUkuran'])->name('transaksi.update.detail.ukuran');


            Route::post('save-bahan-baku', [TransaksiController::class, 'saveBahanBaku'])->name('transaksi.save.bahanbaku');
            Route::put('update-total-transaksi/{id}', [TransaksiController::class, 'updateTotalTransaksi'])->name('transaksi.update.total');
            Route::get('invoice-transaksi/{id}', [TransaksiController::class, 'invoiceTransaksi'])->name('transaksi.invoice');

            // AJAX
            Route::get('get-ajax-bahan-baku/{id}', [TransaksiController::class, 'getAjaxBahanBaku']);
            Route::get('get-ajax-model-to-jenismodel/{id}', [TransaksiController::class, 'getAjaxModelToJenisModel']);
            Route::get('get-ajax-jenismodel-ongkos/{id}', [TransaksiController::class, 'getAjaxModelOngkos']);
        });

        Route::resource('transaksi', TransaksiController::class);
        Route::resource('pelanggan', PelangganController::class);
        Route::resource('modelanda', ModelAndaController::class);
        Route::resource('modelpelanggan', ModelBajuPelangganController::class);
        Route::resource('ukuranpria', UkuranPriaController::class);
        Route::resource('ukuranwanita', UkuranWanitaController::class);
        Route::resource('informasiukuran', InformasiUkuranController::class);
    });

    Route::prefix('produksi')->group(function () {
        Route::prefix('daftar-progres')->group(function () {

        });
        Route::prefix('jadwal-progres')->group(function () {
            Route::get('get-ajax-pemesanan-to-pemesanan-detail/{id}', [JadwalProgresController::class, 'getAjaxPemesanantoPemesananDetail'])->name('get-ajax-pemesanan-to-pemesanan-detail');
            Route::get('get-ajax-perencanaan-produksi-to-pemesanan-detail-edit/{id}', [JadwalProgresController::class, 'getAjaxPerencanaanProduksitoPemesananDetailEdit'])->name('get-ajax-perencanaan-produksi-to-pemesanan-detail-edit');
            Route::get('get-ajax-perencanaan-produksi-to-pemesanan-detail-edit-first/{id}', [JadwalProgresController::class, 'getAjaxPerencanaanProduksitoPemesananDetailEditFirst'])->name('get-ajax-perencanaan-produksi-to-pemesanan-detail-edit-first');
        });
        Route::prefix('peng-bahan-baku')->group(function () {
            Route::get('get-ajax-bahan-baku-first/{id}', [PengunaanBahanBakuController::class, 'getAjaxBahanBaku'])->name('get-ajax-bahan-baku-first');
            Route::get('get-all-ajax-bahan-baku-first/{id}', [PengunaanBahanBakuController::class, 'getAllAjaxBahanBaku'])->name('get-all-ajax-bahan-baku-first');
        });
        Route::prefix('realisasi-progres')->group(function () {
            Route::get('get-ajax-pemesanan-to-pemesanan-detail/{id}', [RealisasiProgresController::class, 'getAjaxPemesanantoPemesananDetail'])->name('realisasi-get-ajax-pemesanan-to-pemesanan-detail');
            Route::get('get-ajax-pemesanan-detail-to-perencanaan-produksi/{id}', [RealisasiProgresController::class, 'getAjaxPemesananDetailtoPerencanaanProduksi'])->name('realisasi-get-ajax-pemesanan-detail-to-perencanaan-produksi');
        });
        Route::resource('daftar-progres', DaftarProgresController::class);
        Route::resource('jadwal-progres', JadwalProgresController::class);
        Route::resource('peng-bahan-baku', PengunaanBahanBakuController::class);
        Route::resource('realisasi-progres', RealisasiProgresController::class);
        Route::resource('laporan-tertanggung', LaporanTertanggungController::class);
    });

    Route::prefix('pengiriman')->group(function () {
        Route::resource('jasaekspedisi', JasaEkspedisiController::class);
        Route::resource('daftar-pengiriman', DaftarPengirimanController::class);
    });

    Route::get('/admin/users', [AdminController::class, 'create'])->name('admin.users');
    Route::post('/admin/users/create', [AdminController::class, 'createUser'])->name('admin.users.create');

});


require __DIR__.'/auth.php';

app/Models/Supplier.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Supplier extends Model
{
    use HasFactory;

    protected $table = 'supplier';
    protected $primaryKey = 'id';
    protected $fillable = [
        'nama_supplier',
        'alamat',
        'email',
        'nomor_telepon',
      ];

}

app/Http/Controllers/SupplierController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\Supplier;
use App\Http\Requests\StoreSupplierRequest;
use App\Http\Requests\UpdateSupplierRequest;

class SupplierController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
          $data = Supplier::all();
          return view('supplier.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('supplier.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreSupplierRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreSupplierRequest $request)
    {
        Supplier::create($request->all());

        if($request){
            return redirect()->route('supplier.index')->with(['success' => 'Data Berhasil Disimpan!']);
        }else{
            return redirect()->route('supplier.index')->with(['error' => 'Data Gagal Disimpan!']);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\DataMaster\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function show(Supplier $supplier)
    {
        return view('supplier.show',compact('supplier'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\DataMaster\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function edit(Supplier $supplier)
    {
        return view('supplier.edit',compact('supplier'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateSupplierRequest  $request
     * @param  \App\Models\DataMaster\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateSupplierRequest $request, Supplier $supplier)
    {
        $supplier->update($request->all());

        if($supplier){
            return redirect()->route('supplier.index')->with(['success' => 'Data Berhasil Diupdate!']);
        }else{
            return redirect()->route('supplier.index')->with(['error' => 'Data Gagal Diupdate!']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\DataMaster\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function destroy(Supplier $supplier)
    {
        $supplier->delete();

        if($supplier){
            return redirect()->route('supplier.index')->with(['success' => 'Data Berhasil Dihapus!']);
        }else{
            return redirect()->route('supplier.index')->with(['error' => 'Data Gagal Dihapus!']);
        }
    }
}

resources/views/supplier/create.blade.php
@extends('layouts.layout')

@section('content')
<!-- BEGIN PAGE HEADER-->
<h3 class="page-title">
    Supplier <br>
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="{{url('/')}}">Dashboard</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="{{route('supplier.index')}}">Pemesanan</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="{{route('supplier.index')}}">Supplier</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="{{route('supplier.create')}}">Tambah Supplier</a>
        </li>
    </ul>
</div>
<!-- END PAGE HEADER-->

<!-- <p>The .table class adds basic styling (light padding and only horizontal dividers) to a table:</p>             -->
<div>
    <div class="portlet">
		<div class="portlet-title">
			<div class="caption">
				<i class="fa fa-reorder"></i> Tambah Supplier
			</div>
		</div>
		<div class="portlet-body form">
			<form method="POST" action="{{ route('supplier.store') }}" enctype="multipart/form-data">
			@csrf
				<div class="form-body">
                    <div class="form-group">
						<label for="nama_supplier">Nama</label>
						<input type="text" class="form-control @error('nama_supplier') is-invalid @enderror" name="nama_supplier" value="{{ old('nama_supplier') }}" placeholder="Isikan nama supplier Anda" required>
						@error('nama_supplier')
							<div class="invalid-feedback" style="color:red">{{ $message }}</div>
						@enderror
					</div><br>
                    <div class="form-group">
						<label for="alamat">Alamat</label>
						<input type="text" class="form-control" name="alamat" value="{{ old('alamat') }}" placeholder="Isikan alamat supplier Anda" required>
					</div><br>
					<div class="form-group">
						<label for="email">Email</label>
						<input type="text" class="form-control" name="email" value="{{ old('email') }}" placeholder="Isikan email supplier Anda" required>
					</div><br>
					<div class="form-group">
						<label for="nomor_telepon">Nomor Telepon</label>
						<input type="text" class="form-control @error('nomor_telepon') is-invalid @enderror" name="nomor_telepon" value="{{ old('nomor_telepon') }}" placeholder="Isikan nomor telepon supplier Anda" required>
					</div><br>
				</div>
				<div class="form-actions">
					<button type="submit" class="btn btn-primary">Simpan</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/supplier/edit.blade.php
@extends('layouts.layout')

@section('content')
<!-- BEGIN PAGE HEADER-->
<h3 class="page-title">
    Supplier <br>
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="{{url('/')}}">Dashboard</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="{{route('supplier.index')}}">Pemesanan</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="{{route('supplier.index')}}">Supplier</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="{{route('supplier.edit', $supplier->id)}}">Ubah Supplier</a>
        </li>
    </ul>
</div>
<!-- END PAGE HEADER-->

<!-- <p>The .table class adds basic styling (light padding and only horizontal dividers) to a table:</p>             -->
<div >
<div class="portlet">
		<div class="portlet-title">
			<div class="caption">
				<i class="fa fa-reorder"></i> Ubah Supplier
			</div>
		</div>
		<div class="portlet-body form">
			<form method="POST" action="{{ route('supplier.update', $supplier->id) }}" enctype="multipart/form-data">
			@csrf
			@method("PUT")
				<div class="form-body">
                    <div class="form-group">
						<label for="nama_supplier">Nama</label>
						<input type="text" class="form-control @error('nama_supplier') is-invalid @enderror" name="nama_supplier" value="{{ old('nama_supplier', $supplier->nama_supplier) }}" placeholder="Isikan nama supplier Anda" required>
						@error('nama_supplier')
							<div class="invalid-feedback" style="color:red">{{ $message }}</div>
						@enderror
					</div><br>
                    <div class="form-group">
						<label for="alamat">Alamat</label>
						<input type="text" class="form-control" name="alamat" value="{{ old('alamat', $supplier->alamat) }}" placeholder="Isikan alamat supplier Anda" required>
					</div><br>
					<div class="form-group">
						<label for="email">Email</label>
						<input type="text" class="form-control" name="email" value="{{ old('email', $supplier->email) }}" placeholder="Isikan email supplier Anda" required>
					</div><br>
					<div class="form-group">
						<label for="nomor_telepon">Nomor Telepon</label>
						<input type="text" class="form-control @error('nomor_telepon') is-invalid @enderror" name="nomor_telepon" value="{{ old('nomor_telepon', $supplier->nomor_telepon) }}" placeholder="Isikan nomor telepon supplier Anda" required>
					</div><br>
				</div>
				<div class="form-actions">
					<button type="submit" class="btn btn-primary">Simpan</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/supplier/index.blade.php
@extends('layouts.layout')

@section('content')
<!-- BEGIN PAGE HEADER-->
<h3 class="page-title">
    Supplier &nbsp;&nbsp;
    @if (auth()->user()->previledge == "Admin")
    <a type= "button" href="{{route('supplier.create')}}" class="btn btn-primary btn-sm">
        + TAMBAH SUPPLIER
    </a>
    @endif
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="{{url('/')}}">Dashboard</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="{{route('supplier.index')}}">Supplier</a>
        </li>
    </ul>
</div>
<!-- END PAGE HEADER-->

@if(session('success'))
<div class="alert alert-success">
    {{ session('success') }}
</div>
@endif

@if (session('error'))
<div class="alert alert-danger">
    {{ session('error') }}
</div>
@endif

<!-- <p>The .table class adds basic styling (light padding and only horizontal dividers) to a table:</p>             -->
<table class="table" id="sample_1">
<thead>
    <tr>
    <!-- <th>ID</th> -->
    <th>Nama</th>
    <th>Alamat</th>
    <th>Email</th>
    <th>Nomor Telepon</th>
    @if (auth()->user()->previledge == "Admin")
    <th>Aksi</th>
    @endif
    </tr>
</thead>
<tbody>
    @foreach($data as $d)
    <tr>
    <td>{{ $d->nama_supplier }}</td>
    <td>{{ $d->alamat }}</td>
    <td>{{ $d->email }}</td>
    <td>{{ $d->nomor_telepon }}</td>
    @if (auth()->user()->previledge == "Admin")
    <td>
        <ul class="nav nav-pills">
            <li >
                <button onclick="window.location='{{ route('supplier.edit', $d->id) }}'" type="button" class="btn btn-success">Ubah</button>
            </li>
            <li>
                <form method="POST" action="{{route('supplier.destroy' , $d->id)}}">
                    @method('DELETE')
                    @csrf
                    <input class="btn btn-danger " type="SUBMIT" value="Hapus"
                    onclick="if(!confirm('Apakah Anda yakin akan menghapus data supplier dan data sediaan bahan baku yang berkaitan?')) {return false;}">
                </form>
            </li>
        </ul>
    </td>
    @endif
    </tr>
    @endforeach
</tbody>
</table>
@endsection

@section('scripts')
<script type="text/javascript" src="{{ asset('assets/plugins/select2/select2.min.js')}}"></script>
<script type="text/javascript" src="{{ asset('assets/plugins/datatables/media/js/jquery.dataTables.min.js')}}"></script>
<script type="text/javascript" src="{{ asset('assets/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js')}}"></script>
<script>
jQuery(document).ready(function() {
	//plugin datatable
	$('#sample_1').DataTable();
});
</script>
@stop