routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\BahanBakuController;
use App\Http\Controllers\BerandaController;
use App\Http\Controllers\BillOfMaterialController;
use App\Http\Controllers\DaftarPengirimanController;
use App\Http\Controllers\ModelAndaController;
use App\Http\Controllers\ModelBajuPelangganController;
use App\Http\Controllers\PelangganController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\DaftarProgresController;
use App\Http\Controllers\InformasiUkuranController;
use App\Http\Controllers\JadwalProgresController;
use App\Http\Controllers\JasaEkspedisiController;
use App\Http\Controllers\KolomRakController;
use App\Http\Controllers\LaporanTertanggungController;
use App\Http\Controllers\PengunaanBahanBakuController;
use App\Http\Controllers\RealisasiProgresController;
use App\Http\Controllers\TransaksiBahanBakuController;
use App\Http\Controllers\TransaksiController;
use App\Http\Controllers\UkuranPriaController;
use App\Http\Controllers\UkuranWanitaController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

// Route::get('/dashboard', function () {
//     return view('beranda');
// })->middleware(['auth'])->name('dashboard');

Route::middleware(['auth'])->group(function () {

    Route::get('/dashboard', [BerandaController::class, 'dashboard'])->name('dashboard');

    Route::prefix('bahan-baku')->group(function () {
        Route::get('tambah-detail-transaksi-bahanbaku/{id}', [TransaksiBahanBakuController::class, 'createDetail'])->name('transaksi.bahanbaku.detail.create');
        Route::post('save-detail-transaksi-bahanbaku', [TransaksiBahanBakuController::class, 'saveDetail'])->name('transaksi.bahanbaku.save.detail');
        Route::get('edit-detail-transaksi-bahanbaku/{id}', [TransaksiBahanBakuController::class, 'editDetailTransaksi'])->name('transaksi.bahanbaku.detail.edit');
        Route::put('update-detail-transaksi-bahanbaku/{id}', [TransaksiBahanBakuController::class, 'updateDetailTransaksi'])->name('transaksi.bahanbaku.update.detail');
        Route::put('update-transaksi-totalbayar/{id}/update', [TransaksiBahanBakuController::class, 'updateTransaksiTotalbayar'])->name('transaksi.update.totalbayar');
        Route::get('get-ajax-bahan-baku/{id}', [TransaksiBahanBakuController::class, 'getAjaxBahanBaku'])->name('get-ajax-bahan-baku');
        Route::get('tambah-detail-bom/{id}', [BillOfMaterialController::class, 'createDetail'])->name('bom.detail.create');
        Route::post('save-detail-bom', [BillOfMaterialController::class, 'saveDetail'])->name('bom.detail.save');
        Route::get('edit-detail-bom/{id}', [BillOfMaterialController::class, 'editDetail'])->name('bom.detail.edit');
        Route::put('update-detail-bom/{id}', [BillOfMaterialController::class, 'updateDetail'])->name('bom.detail.update');



        Route::resource('transaksi-bahanbaku', TransaksiBahanBakuController::class);
        Route::resource('supplier', SupplierController::class);
        Route::resource('bahanbaku', BahanBakuController::class);
        Route::resource('kolomrak', KolomRakController::class);
        Route::resource('bom', BillOfMaterialController::class);
    });

    Route::prefix('pemesanan')->group(function () {
        Route::prefix('transaksi')->group(function () {
            Route::get('tambah-detail-transaksi/{id}', [TransaksiController::class, 'createDetailTransaksi'])->name('transaksi.detail.create');
            Route::post('save-detail-transaksi', [TransaksiController::class, 'saveDetail'])->name('transaksi.save.detail');
            Route::get('edit-detail-transaksi/{id}', [TransaksiController::class, 'editDetailTransaksi'])->name('transaksi.detail.edit');
            Route::post('update-detail-transaksi', [TransaksiController::class, 'updateDetailTransaksi'])->name('transaksi.update.detail');
            Route::get('tambah-detail-transaksi-ukuran/{id}', [TransaksiController::class, 'createDetailTransaksiUkuran'])->name('transaksi.detail.ukuran.create');
            Route::post('save-detail-transaksi-ukuran', [TransaksiController::class, 'saveDetailUkuran'])->name('transaksi.save.detail.ukuran');
            Route::get('edit-detail-transaksi-ukuran/{id}', [TransaksiController::class, 'editDetailUkuran'])->name('transaksi.edit.detail.ukuran');
            Route::post('update-detail-transaksi-ukuran', [TransaksiController::class, 'updateDetailUkuran'])->name('transaksi.update.detail.ukuran');


            Route::post('save-bahan-baku', [TransaksiController::class, 'saveBahanBaku'])->name('transaksi.save.bahanbaku');
            Route::put('update-total-transaksi/{id}', [TransaksiController::class, 'updateTotalTransaksi'])->name('transaksi.update.total');
            Route::get('invoice-transaksi/{id}', [TransaksiController::class, 'invoiceTransaksi'])->name('transaksi.invoice');

            // AJAX
            Route::get('get-ajax-bahan-baku/{id}', [TransaksiController::class, 'getAjaxBahanBaku']);
            Route::get('get-ajax-model-to-jenismodel/{id}', [TransaksiController::class, 'getAjaxModelToJenisModel']);
            Route::get('get-ajax-jenismodel-ongkos/{id}', [TransaksiController::class, 'getAjaxModelOngkos']);
        });

        Route::resource('transaksi', TransaksiController::class);
        Route::resource('pelanggan', PelangganController::class);
        Route::resource('modelanda', ModelAndaController::class);
        Route::resource('modelpelanggan', ModelBajuPelangganController::class);
        Route::resource('ukuranpria', UkuranPriaController::class);
        Route::resource('ukuranwanita', UkuranWanitaController::class);
        Route::resource('informasiukuran', InformasiUkuranController::class);
    });

    Route::prefix('produksi')->group(function () {
        Route::prefix('daftar-progres')->group(function () {

        });
        Route::prefix('jadwal-progres')->group(function () {
            Route::get('get-ajax-pemesanan-to-pemesanan-detail/{id}', [JadwalProgresController::class, 'getAjaxPemesanantoPemesananDetail'])->name('get-ajax-pemesanan-to-pemesanan-detail');
            Route::get('get-ajax-perencanaan-produksi-to-pemesanan-detail-edit/{id}', [JadwalProgresController::class, 'getAjaxPerencanaanProduksitoPemesananDetailEdit'])->name('get-ajax-perencanaan-produksi-to-pemesanan-detail-edit');
            Route::get('get-ajax-perencanaan-produksi-to-pemesanan-detail-edit-first/{id}', [JadwalProgresController::class, 'getAjaxPerencanaanProduksitoPemesananDetailEditFirst'])->name('get-ajax-perencanaan-produksi-to-pemesanan-detail-edit-first');
        });
        Route::prefix('peng-bahan-baku')->group(function () {
            Route::get('get-ajax-bahan-baku-first/{id}', [PengunaanBahanBakuController::class, 'getAjaxBahanBaku'])->name('get-ajax-bahan-baku-first');
            Route::get('get-all-ajax-bahan-baku-first/{id}', [PengunaanBahanBakuController::class, 'getAllAjaxBahanBaku'])->name('get-all-ajax-bahan-baku-first');
        });
        Route::prefix('realisasi-progres')->group(function () {
            Route::get('get-ajax-pemesanan-to-pemesanan-detail/{id}', [RealisasiProgresController::class, 'getAjaxPemesanantoPemesananDetail'])->name('realisasi-get-ajax-pemesanan-to-pemesanan-detail');
            Route::get('get-ajax-pemesanan-detail-to-perencanaan-produksi/{id}', [RealisasiProgresController::class, 'getAjaxPemesananDetailtoPerencanaanProduksi'])->name('realisasi-get-ajax-pemesanan-detail-to-perencanaan-produksi');
        });
        Route::resource('daftar-progres', DaftarProgresController::class);
        Route::resource('jadwal-progres', JadwalProgresController::class);
        Route::resource('peng-bahan-baku', PengunaanBahanBakuController::class);
        Route::resource('realisasi-progres', RealisasiProgresController::class);
        Route::resource('laporan-tertanggung', LaporanTertanggungController::class);
    });

    Route::prefix('pengiriman')->group(function () {
        Route::resource('jasaekspedisi', JasaEkspedisiController::class);
        Route::resource('daftar-pengiriman', DaftarPengirimanController::class);
    });

    Route::get('/admin/users', [AdminController::class, 'create'])->name('admin.users');
    Route::post('/admin/users/create', [AdminController::class, 'createUser'])->name('admin.users.create');

});


require __DIR__.'/auth.php';

app/Models/KolomRak.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class KolomRak extends Model
{
    use HasFactory;

    protected $table = 'kolom_rak';
    protected $primaryKey = 'id';
    protected $fillable = [
        'nama_rak',
        'nama_kolom'
      ];

}

app/Http/Controllers/KolomRakController.php
<?php

namespace App\Http\Controllers;

use App\Models\KolomRak;
use Illuminate\Http\Request;

class KolomRakController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
          $data = KolomRak::all();
          return view('kolomrak.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('kolomrak.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreSupplierRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        KolomRak::create($request->all());

        if($request){
            return redirect()->route('kolomrak.index')->with(['success' => 'Data Berhasil Disimpan!']);
        }else{
            return redirect()->route('kolomrak.index')->with(['error' => 'Data Gagal Disimpan!']);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\DataMaster\KolomRak  $kolomrak
     * @return \Illuminate\Http\Response
     */
    public function show(KolomRak $kolomrak)
    {
        return view('kolomrak.show',compact('kolomrak'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\DataMaster\KolomRak  $kolomrak
     * @return \Illuminate\Http\Response
     */
    public function edit(KolomRak $kolomrak)
    {
        return view('kolomrak.edit',compact('kolomrak'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateSupplierRequest  $request
     * @param  \App\Models\DataMaster\KolomRak  $kolomrak
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, KolomRak $kolomrak)
    {
        $kolomrak->update($request->all());

        if($kolomrak){
            return redirect()->route('kolomrak.index')->with(['success' => 'Data Berhasil Diupdate!']);
        }else{
            return redirect()->route('kolomrak.index')->with(['error' => 'Data Gagal Diupdate!']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\DataMaster\KolomRak  $kolomrak
     * @return \Illuminate\Http\Response
     */
    public function destroy(KolomRak $kolomrak)
    {
        $kolomrak->delete();

        if($kolomrak){
            return redirect()->route('kolomrak.index')->with(['success' => 'Data Berhasil Dihapus!']);
        }else{
            return redirect()->route('kolomrak.index')->with(['error' => 'Data Gagal Dihapus!']);
        }
    }
}

resources/views/kolomrak/create.blade.php
@extends('layouts.layout')

@section('content')
<!-- BEGIN PAGE HEADER-->
<h3 class="page-title">
    Kolom Rak <br>
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="{{url('/')}}">Dashboard</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="{{route('kolomrak.index')}}">Pemesanan</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="{{route('kolomrak.index')}}">Kolom Rak</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="{{route('kolomrak.create')}}">Tambah Kolom Rak</a>
        </li>
    </ul>
</div>
<!-- END PAGE HEADER-->

<!-- <p>The .table class adds basic styling (light padding and only horizontal dividers) to a table:</p>             -->
<div>
    <div class="portlet">
		<div class="portlet-title">
			<div class="caption">
				<i class="fa fa-reorder"></i> Tambah Kolom Rak
			</div>
		</div>
		<div class="portlet-body form">
			<form method="POST" action="{{ route('kolomrak.store') }}" enctype="multipart/form-data">
			@csrf
				<div class="form-body">
                    <div class="form-group">
						<label for="nama_rak">Nama Rak</label>
						<input type="text" class="form-control @error('nama_rak') is-invalid @enderror" name="nama_rak" value="{{ old('nama_rak') }}" placeholder="Isikan nama rak" required>
						@error('nama_rak')
							<div class="invalid-feedback" style="color:red">{{ $message }}</div>
						@enderror
					</div>
                    <div class="form-group">
						<label for="nama_kolom">Nama Kolom</label>
						<input type="text" class="form-control @error('nama_kolom') is-invalid @enderror" name="nama_kolom" value="{{ old('nama_kolom') }}" placeholder="Isikan nama kolom" required>
						@error('nama_kolom')
							<div class="invalid-feedback" style="color:red">{{ $message }}</div>
						@enderror
					</div>
				</div>
				<div class="form-actions">
					<button type="submit" class="btn btn-primary">Simpan</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/kolomrak/edit.blade.php
@extends('layouts.layout')

@section('content')
<!-- BEGIN PAGE HEADER-->
<h3 class="page-title">
    Kolom Rak <br>
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="{{url('/')}}">Dashboard</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="{{route('kolomrak.index')}}">Bahan Baku</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="{{route('kolomrak.index')}}">Kolom Rak</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="{{route('kolomrak.edit', $kolomrak->id)}}">Ubah Kolom Rak</a>
        </li>
    </ul>
</div>
<!-- END PAGE HEADER-->

<!-- <p>The .table class adds basic styling (light padding and only horizontal dividers) to a table:</p>             -->
<div >
<div class="portlet">
		<div class="portlet-title">
			<div class="caption">
				<i class="fa fa-reorder"></i> Ubah Kolom Rak
			</div>
		</div>
		<div class="portlet-body form">
			<form method="POST" action="{{ route('kolomrak.update', $kolomrak->id) }}" enctype="multipart/form-data">
			@csrf
			@method("PUT")
				<div class="form-body">
                    <div class="form-group">
						<label for="nama_rak">Nama Rak</label>
						<input type="text" class="form-control @error('nama_rak') is-invalid @enderror" name="nama_rak" value="{{ old('nama_rak', $kolomrak->nama_rak) }}" placeholder="Isikan nama rak" required>
						@error('nama_rak')
							<div class="invalid-feedback" style="color:red">{{ $message }}</div>
						@enderror
					</div>
                    <div class="form-group">
						<label for="nama_kolom">Nama Kolom</label>
						<input type="text" class="form-control @error('nama_kolom') is-invalid @enderror" name="nama_kolom" value="{{ old('nama_kolom', $kolomrak->nama_kolom) }}" placeholder="Isikan nama kolom" required>
						@error('nama_kolom')
							<div class="invalid-feedback" style="color:red">{{ $message }}</div>
						@enderror
					</div>
				</div>
				<div class="form-actions">
					<button type="submit" class="btn btn-primary">Simpan</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/kolomrak/index.blade.php
@extends('layouts.layout')

@section('content')
<!-- BEGIN PAGE HEADER-->
<h3 class="page-title">
    Kolom Rak &nbsp;&nbsp;
    @if (auth()->user()->previledge == "Admin")
        <a type= "button" href="{{route('kolomrak.create')}}" class="btn btn-primary btn-sm">
            + Tambah Kolom Rak
        </a>
    @endif
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="{{url('/')}}">Dashboard</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="{{route('kolomrak.index')}}">Kolom Rak</a>
        </li>
    </ul>
</div>
<!-- END PAGE HEADER-->

@if(session('success'))
<div class="alert alert-success">
    {{ session('success') }}
</div>
@endif

@if (session('error'))
<div class="alert alert-danger">
    {{ session('error') }}
</div>
@endif

<!-- <p>The .table class adds basic styling (light padding and only horizontal dividers) to a table:</p>             -->
<table class="table" id="sample_1">
<thead>
    <tr>
    <th>Nama Rak</th>
    <th>Nama Kolom</th>
    @if (auth()->user()->previledge == "Admin")
    <th>Aksi</th>
    @endif
    </tr>
</thead>
<tbody>
    @foreach($data as $d)
    <tr>
    <td>{{ $d->nama_rak }}</td>
    <td>{{ $d->nama_kolom }}</td>
    @if (auth()->user()->previledge == "Admin")
    <td>
        <ul class="nav nav-pills">
            <li >
                <button onclick="window.location='{{ route('kolomrak.edit', $d->id) }}'" type="button" class="btn btn-success">Ubah</button>
            </li>
            <li>
                <form method="POST" action="{{route('kolomrak.destroy' , $d->id)}}">
                    @method('DELETE')
                    @csrf
                    <input class="btn btn-danger " type="SUBMIT" value="Hapus"
                    onclick="if(!confirm('Apakah Anda yakin akan menghapus data kolom rak dan data sediaan bahan baku yang berkaitan?')) {return false;}">
                </form>
            </li>
        </ul>
    </td>
    @endif
    </tr>
    @endforeach
</tbody>
</table>
@endsection

@section('scripts')
<script type="text/javascript" src="{{ asset('assets/plugins/select2/select2.min.js')}}"></script>
<script type="text/javascript" src="{{ asset('assets/plugins/datatables/media/js/jquery.dataTables.min.js')}}"></script>
<script type="text/javascript" src="{{ asset('assets/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js')}}"></script>
<script>
jQuery(document).ready(function() {
	//plugin datatable
	$('#sample_1').DataTable();
});
</script>
@stop